# Generated by Django 4.1.5 on 2023-01-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChargingStation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socketType', models.CharField(choices=[('F', 'Fast'), ('R', 'Rapid'), ('S', 'Slow')], default='S', max_length=1)),
                ('socketStatus', models.CharField(choices=[('Y', 'Available'), ('N', 'UNAVAILABLE')], default='Y', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sockets', to='ChargingStation.chargingstation')),
            ],
        ),
    ]
