# Generated by Django 4.1.5 on 2023-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='socketStatus',
            field=models.CharField(choices=[('Y', 'Available'), ('N', 'Unavailable')], default='Y', max_length=1),
        ),
    ]
