# Generated by Django 4.1.5 on 2023-01-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0002_alter_socket_socketstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socket',
            old_name='socketStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='socket',
            old_name='socketType',
            new_name='type',
        ),
    ]
