# Generated by Django 4.1.5 on 2023-01-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0004_sockets_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='status',
            field=models.CharField(choices=[('Y', 'Available'), ('N', 'Unavailable'), ('C', 'Charging')], default='Y', max_length=1),
        ),
    ]
