# Generated by Django 4.1.5 on 2023-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0005_alter_socket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='connectedUserEmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
