# Generated by Django 4.1.5 on 2023-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('discount_amount', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
