# Generated by Django 4.1.5 on 2023-01-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_alter_discount_discount_amount'),
        ('ChargingStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='active_discount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Discount.discount'),
        ),
    ]
