# Generated by Django 4.1.5 on 2023-01-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0002_chargingstation_active_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='active_discount',
        ),
    ]
