# Generated by Django 4.1.5 on 2023-01-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0003_bss_isactive'),
        ('ChargingStation', '0004_alter_chargingstation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='activeDso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_dso', to='EnergyProvider.dso'),
        ),
    ]
