# Generated by Django 4.1.5 on 2023-01-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0006_alter_chargingstation_activedso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='activeDso',
        ),
    ]
