# Generated by Django 4.1.5 on 2023-01-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0004_bss_currentenergy_alter_bss_capacity_and_more'),
        ('ChargingStation', '0009_alter_chargingstation_activedso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='activeDso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_dso', to='EnergyProvider.dso'),
        ),
    ]
