# Generated by Django 4.1.5 on 2023-01-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0010_alter_chargingstation_activedso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='activeDso',
            new_name='active_dso',
        ),
    ]
