# Generated by Django 4.1.5 on 2023-01-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0005_remove_dso_station'),
        ('ChargingStation', '0012_chargingstation_connected_dsos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='active_dso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_dso', to='EnergyProvider.dso'),
        ),
    ]
