# Generated by Django 4.1.5 on 2023-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0014_alter_chargingstation_connected_dsos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='city',
            field=models.CharField(default='Milan', max_length=255),
        ),
    ]
