# Generated by Django 4.1.5 on 2023-01-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0004_alter_chargingstation_address'),
        ('EnergyProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bss',
            name='station',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connected_bss', to='ChargingStation.chargingstation'),
        ),
        migrations.AddField(
            model_name='dso',
            name='station',
            field=models.ManyToManyField(related_name='connected_dso', to='ChargingStation.chargingstation'),
        ),
    ]
