# Generated by Django 4.1.5 on 2023-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0002_bss_station_dso_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='bss',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
