# Generated by Django 4.1.5 on 2023-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0003_bss_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bss',
            name='currentEnergy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bss',
            name='capacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='bss',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
