# Generated by Django 4.1.5 on 2023-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0004_bss_currentenergy_alter_bss_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dso',
            name='station',
        ),
    ]
