# Generated by Django 4.1.5 on 2023-01-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyProvider', '0006_dso_example'),
        ('EnergyProvider', '0007_battery_example'),
    ]

    operations = [
    ]
