# Generated by Django 4.1.5 on 2023-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpms',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
