# Generated by Django 4.1.5 on 2023-01-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
