# Generated by Django 4.1.5 on 2023-01-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='cpmsID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='socketID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stationID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
