# Generated by Django 4.1.5 on 2023-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_booking_start_time_booking_cpmsid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stationAddress',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
