# Generated by Django 4.1.5 on 2023-01-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingStation', '0004_alter_chargingstation_address'),
        ('Booking', '0002_remove_booking_start_time_booking_chargingstation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chargingStation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ChargingStation.chargingstation'),
        ),
    ]
