# Generated by Django 4.1.5 on 2023-01-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0003_rename_socketstatus_socket_status_and_more'),
        ('Booking', '0003_alter_booking_chargingstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='socket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookingSocket', to='Socket.socket'),
        ),
    ]
