# Generated by Django 4.1.5 on 2023-01-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0003_rename_socketstatus_socket_status_and_more'),
        ('Booking', '0004_booking_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingSocket', to='Socket.socket'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.EmailField(default=None, max_length=255, verbose_name='email address'),
        ),
    ]
